import Head from 'next/head'
import Image from 'next/image'
import React, {useRef} from 'react'
import { Canvas, useFrame } from '@react-three/fiber'
import Banner from '@/components/Banner'
import Header from '@/components/Header'
import Navbar from '@/components/Navbar'
import About from '@/components/About'
import Projects from '@/components/Projects'
import Connect from '@/components/Connect'

import Skills from '@/components/Skills'
export default function Home() {
  return (
    <>
      <Head>
        <title>DevFolk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Canvas
        style={{
          position: "fixed",
          top: 0,
          left: 0,
          zIndex: "-1",
        }}    
      >
        <ambientLight intensity={0.8} />
        <spotLight position={[10, 10, 10]} angle={1} />
        <pointLight
            position={[10, -5, -15]}
            intensity={0.8}
           color={"orange"}
        />  
        <ThreeBack />
     
      </Canvas>
      <div className='bg-[#'>
        <Header />
        {/* <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
          <div>
            <LeftSide />
          </div>
        </div> */}
        <Banner />
        <Navbar />
        <About />
        <Skills />
        <Projects />
        <Connect />
        <div className='h-[600px] lg:h-0'></div>
      </div>
    </>
  )
};
function ThreeBack(props) {
  const mesh = useRef();

  useFrame(() => {
      mesh.current.rotation.x = mesh.current.rotation.y += 0.0008;
  });

  return (
    <mesh {...props} ref={mesh} scale={1}>
    <sphereGeometry args={[6, 15]} />
    <meshStandardMaterial wireframe color={"#024972"} />
</mesh>
  );
}
